<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="social_net" nsURI="http://www.example.org/social_net" nsPrefix="social_net">
  <eClassifiers xsi:type="ecore:EClass" name="Topic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time_stmp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" eOpposite="#//Comment/subject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"
        eOpposite="#//User/topics"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replied_topic_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="likes" upperBound="-1"
        eType="#//Like" eOpposite="#//Like/likedComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//Topic" eOpposite="#//Topic/comments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post" eSuperTypes="#//Topic"/>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friendships" upperBound="-1"
        eType="#//Friendship" eOpposite="#//Friendship/friends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenLikes" upperBound="-1"
        eType="#//Like" eOpposite="#//Like/user"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" eOpposite="#//Topic/author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Friendship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time_stmp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friends" lowerBound="2"
        upperBound="2" eType="#//User" eOpposite="#//User/friendships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Like">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time_stmp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"
        eOpposite="#//User/givenLikes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="likedComment" lowerBound="1"
        eType="#//Comment" eOpposite="#//Comment/likes"/>
  </eClassifiers>
</ecore:EPackage>
